"""New user fields

Revision ID: 738c8da2675a
Revises: 7a4cd160f7fe
Create Date: 2018-12-06 10:52:50.313940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738c8da2675a'
down_revision = '7a4cd160f7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
